### PR TITLE
added connection_name output

### PR DESCRIPTION
**Pull request by Eraac**
Added missing output for https://github.com/GoogleCloudPlatform/terraform-google-sql-db/issues/13

### CODE REVIEW

**Comment by Eraac** [comment]
I signed it!

**Comment by Eraac** [comment]
Does something missing for be merged?

**Comment by namusyaka** [comment]
Sorry for the late response.
This module has been updated drastically in #21.
In the PR, main module is separated into two modules, mysql and postgresql. They have already `connection_name` in [outputs.tf](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/blob/9e22cb7dfebb4c14faec66481a762d3d464b7cb9/modules/mysql/outputs.tf#L33). If you're satisfied by the change, please close this pull request.

**Comment by Eraac** [comment]
Nice! Good to know thank you :smile:

**Pull request closed without merging**
